apiVersion: v1
kind: Service
metadata:
  labels:
    app: whisper
  name: whisper
  namespace: smarthome
spec:
  ports:
  - name: whisper
    port: 10300
    targetPort: whisper
  selector:
    app: whisper
  type: ClusterIP
