---
dns_zone_name: local-domain
dns_record_type: A
dns_server_ip: 1.1.1.1
dns_key_name: dnsUpdateAnsible
dns_key_secret: dns update secret

k3s_master_domain_name: k3s.local-domain
k3s_cluster_name: k3s

k3s_master_ingress_ip: 123.456.789.123
